backend:
  name: git-gateway
  branch: main  # Change to your main branch name


collections:
  - name: "products"
    label: "Products"
    folder: "src/content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "price", label: "Price", widget: "number" }
      - { name: "image", label: "Image", widget: "image" }
      - { name: "description", label: "Description", widget: "markdown" }
